/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rmartinez
 */
public class Sql {

    public static String SQL_INICIO = "declare @fechaActual datetime= '???'  "
            + "SELECT A.* INTO  #TMP_BilVentasPendientes  "
            + "FROM  "
            + "(  "
            + "SELECT     GETDATE() AS FechaRegistro, admAtencion.IdAtencion, SUM(Ventas.vrVentas) AS Causacion, proProducto.CodProducto, proProducto.NomProducto,   "
            + "                      admCliente.ApeCliente + ' ' + admCliente.NomCliente AS Paciente, admCliente.NumDocumento, admAtencion.IndActivado, genTercero.NomTercero,   "
            + "                      proProductoTipo.NomProductoTipo, proGrupoProducto.NomGrupo, Ventas.VenFec, Ventas.VenNum, Ventas.VenUbiCon, Ventas.VenDetValDes,   "
            + "                      Ventas.VenDetCofIde, Ventas.VenDetDecIde, BILCONTRATOSDESCUENTOS.DecIde, BILCONTRATOSDESCUENTOS.DecVal,   "
            + "                      BILCONFIGURACIONHONO.TerIde, BILCONFIGURACIONHONO.CofPorTar, BILCONFIGURACIONHONO.CofPorDes, BILCONFIGURACIONHONO.CofPorTra,   "
            + "                      proProducto.IdProducto, proGrupoProducto.IdGrupo, proProductoTipo.IdProductoTipo, admAtencion.FecIngreso, genTercero.IdTercero,   "
            + "                      conContrato.DesContrato, admAtencion.IdUbicacionActual, BILCONTRATOSDESCUENTOS.DecProIde, genTercero_1.NomTercero AS Resp,   "
            + "                      conContrato.IdContrato, admAtencion.FecEgreso  "
            + "FROM         proGrupoProducto INNER JOIN  "
            + "                      proProducto ON proGrupoProducto.IdGrupo = proProducto.IdGrupo INNER JOIN  "
            + "                      proProductoTipo ON proProducto.IdProductoTipo = proProductoTipo.IdProductoTipo RIGHT OUTER JOIN  "
            + "                      genTercero AS genTercero_1 INNER JOIN  "
            + "                          (SELECT     BILVENTASDETALLE.VenDetDecIde, BILVENTASDETALLE.VenDetCofIde, BILVENTAS.VenFec, BILVENTAS.VenNum,   "
            + "                                                   BILVENTAS.VenUbiCon, BILVENTASDETALLE.VenDetValDes, BILVENTAS.SubAteIde, BILVENTASDETALLE.ProIde,   "
            + "                                                   SUM((BILVENTASDETALLE.VenDetCan - BILVENTASDETALLE.VenDetCanDev)   "
            + "                                                   * BILVENTASDETALLE.VenDetVal + BILVENTASDETALLE.VenDetValRec - BILVENTASDETALLE.VenDetValDes) AS vrVentas  "
            + "                            FROM          BILVENTAS WITH (NOLOCK) INNER JOIN  "
            + "                                                   BILVENTASDETALLE WITH (NOLOCK) ON BILVENTAS.EntCod = BILVENTASDETALLE.EntCod AND   "
            + "                                                   BILVENTAS.VenTraIde = BILVENTASDETALLE.VenTraIde AND BILVENTAS.VenNum = BILVENTASDETALLE.VenNum  "
            + "                            WHERE      (BILVENTAS.VenEst IN ('S')) and (BILVENTAS.VenFec)<= @fechaActual "
            + "                            GROUP BY BILVENTAS.SubAteIde, BILVENTASDETALLE.ProIde, BILVENTAS.VenFec, BILVENTAS.VenNum, BILVENTAS.VenUbiCon,   "
            + "                                                   BILVENTASDETALLE.VenDetValDes, BILVENTASDETALLE.VenDetDecIde, BILVENTASDETALLE.VenDetCofIde  "
            + "                            UNION ALL  "
            + "                            SELECT     VenDetCofIde, VenDetDecIde, VenFec, VenNum, VenUbiCon,VenDetValDes, SubAteIde, ProIde,  SUM(vrVentas) AS vrVentas  "
            + "                            FROM         (SELECT     (SELECT     (BILVENTASDETALLE_1.VenDetCan - BILVENTASDETALLE_1.VenDetCanDev - ISNULL  "
            + "                                                                                                      ((SELECT     SUM(BILFACTURADETALLE.FacDetCan) AS Expr1  "
            + "                                                                                                          FROM         BILFACTURADETALLE WITH (nolock) INNER JOIN  "
            + "                                                                                                                                BILFACTURA WITH (nolock) ON BILFACTURADETALLE.EntCod = BILFACTURA.EntCod AND   "
            + "                                                                                                                                BILFACTURADETALLE.FacSecCod = BILFACTURA.FacSecCod AND   "
            + "                                                                                                                                BILFACTURADETALLE.FacNum = BILFACTURA.FacNum AND   "
            + "                                                                                                                                BILFACTURADETALLE.FacTimIde = BILFACTURA.FacTimIde AND   "
            + "                                                                                                                                BILFACTURADETALLE.FacMosCod = BILFACTURA.FacMosCod AND   "
            + "                                                                                                                                BILFACTURADETALLE.VenTraIde = BILVENTASDETALLE_1.VenTraIde AND   "
            + "                                                                                                                                BILFACTURADETALLE.VenNum = BILVENTASDETALLE_1.VenNum AND   "
            + "                                                                                                                                BILFACTURADETALLE.ProIde = BILVENTASDETALLE_1.ProIde AND   "
            + "                                                                                                                                BILFACTURADETALLE.VenDetLot = BILVENTASDETALLE_1.VenDetLot  "
            + "                                                                                                          WHERE     (BILFACTURA.FacEst <> 'E')), 0))   "
            + "                                                                                                  * BILVENTASDETALLE_1.VenDetVal + BILVENTASDETALLE_1.VenDetValRec - BILVENTASDETALLE_1.VenDetValDes AS  "
            + "                                                                                                   X) AS vrVentas, BILVENTASDETALLE_1.ProIde, BILVENTAS_1.SubAteIde, BILVENTAS_1.VenFec,   "
            + "                                                                          BILVENTAS_1.VenNum, BILVENTAS_1.VenUbiCon, BILVENTAS_1.VenEst, BILVENTASDETALLE_1.VenDetValDes,   "
            + "                                                                          BILVENTASDETALLE_1.VenDetDecIde, BILVENTASDETALLE_1.VenDetCofIde  "
            + "                                                   FROM          BILVENTAS AS BILVENTAS_1 WITH (NOLOCK) INNER JOIN  "
            + "                                                                          BILVENTASDETALLE AS BILVENTASDETALLE_1 WITH (NOLOCK) ON   "
            + "                                                                          BILVENTAS_1.EntCod = BILVENTASDETALLE_1.EntCod AND BILVENTAS_1.VenTraIde = BILVENTASDETALLE_1.VenTraIde AND   "
            + "                                                                          BILVENTAS_1.VenNum = BILVENTASDETALLE_1.VenNum  "
            + "                                                   WHERE      (BILVENTAS_1.VenEst IN ('P')) and (BILVENTAS_1.VenFec)<= @fechaActual  "
            + "																) AS VentasParciales  "
            + "                            GROUP BY SubAteIde, ProIde, VenFec, VenNum, VenUbiCon, VenDetValDes, VenDetDecIde, VenDetCofIde) AS Ventas INNER JOIN  "
            + "                      BILCONFIGURACIONHONO ON Ventas.VenDetCofIde = BILCONFIGURACIONHONO.CofIde ON   "
            + "                      genTercero_1.IdTercero = BILCONFIGURACIONHONO.TerIde LEFT OUTER JOIN  "
            + "                      BILCONTRATOSDESCUENTOS ON Ventas.VenDetDecIde = BILCONTRATOSDESCUENTOS.DecIde ON   "
            + "                      proProducto.IdProducto = Ventas.ProIde LEFT OUTER JOIN  "
            + "                      genUbicacion INNER JOIN  "
            + "                      genTercero WITH (nolock) INNER JOIN  "
            + "                      conContrato ON genTercero.IdTercero = conContrato.IdTercero INNER JOIN  "
            + "                      ADMATENCIONESVINCULA WITH (nolock) INNER JOIN  "
            + "                      admCliente WITH (nolock) INNER JOIN  "
            + "                      admAtencion WITH (nolock) ON admCliente.IdCliente = admAtencion.IdCliente ON ADMATENCIONESVINCULA.AteIde = admAtencion.IdAtencion ON   "
            + "                      conContrato.IdContrato = ADMATENCIONESVINCULA.ConIde ON genUbicacion.IdUbicacion = admAtencion.IdUbicacionActual ON   "
            + "                      Ventas.SubAteIde = admAtencion.IdAtencion AND ADMATENCIONESVINCULA.AtnOrdPri = 1 AND ADMATENCIONESVINCULA.AtnIndAct = 1  "
            + "GROUP BY admAtencion.IdAtencion, proProducto.CodProducto, proProducto.NomProducto, admCliente.ApeCliente, admCliente.NomCliente,   "
            + "                      admCliente.NumDocumento, admAtencion.IndActivado, genTercero.NomTercero, proProductoTipo.NomProductoTipo, proGrupoProducto.NomGrupo,   "
            + "                      Ventas.VenFec, Ventas.VenNum, Ventas.VenUbiCon, Ventas.VenDetValDes, Ventas.VenDetDecIde, BILCONTRATOSDESCUENTOS.DecIde,   "
            + "                      BILCONTRATOSDESCUENTOS.DecVal, Ventas.VenDetCofIde, BILCONFIGURACIONHONO.TerIde, BILCONFIGURACIONHONO.CofPorTar,   "
            + "                      BILCONFIGURACIONHONO.CofPorDes, BILCONFIGURACIONHONO.CofPorTra, proProducto.IdProducto, proGrupoProducto.IdGrupo,   "
            + "                      proProductoTipo.IdProductoTipo, admAtencion.FecIngreso, genTercero.IdTercero, conContrato.DesContrato, admAtencion.IdUbicacionActual,   "
            + "                      BILCONTRATOSDESCUENTOS.DecProIde, genTercero_1.NomTercero, conContrato.IdContrato, admAtencion.FecEgreso  "
            + "  "
            + "UNION ALL  "
            + "SELECT DISTINCT   "
            + "                      GETDATE() AS FechaRegistro, BILVENTAS.SubAteIde, SUM(C.VenDetTicCan * C.VenDetTicVal) AS causacion, C.CodProducto, C.NomProducto,   "
            + "                      admCliente.ApeCliente + ' ' + admCliente.NomCliente AS paciente, admCliente.NumDocumento, admAtencion.IndActivado, genTercero_1.NomTercero,   "
            + "                      'Componentes' AS NomProductoTipo, C.NomGrupo, BILVENTAS.VenFec, BILVENTAS.VenNum,BILVENTAS.VenUbiEnt, C.VenDetTicValDes, C.VenDetTicPerCofIde,   "
            + "                      C.VenDetTicDecIde, BILCONTRATOSDESCUENTOS.DecIde, BILCONTRATOSDESCUENTOS.DecVal, C.VenDetTicTerIde,   "
            + "                      BILCONFIGURACIONHONO.CofPorTar, BILCONFIGURACIONHONO.CofPorDes, BILCONFIGURACIONHONO.CofPorTra, C.VenDetTicProIde, C.IdGrupo,   "
            + "                      C.IdProductoTipo, admAtencion.FecIngreso, conContrato.IdTercero, conContrato.DesContrato, admAtencion.IdUbicacionActual,  C.ProIde,   "
            + "                      genTercero.NomTercero AS Resp, conContrato.IdContrato, admAtencion.FecEgreso  "
            + "FROM         genTercero INNER JOIN  "
            + "                          (SELECT     BILVENTASCOMPONENTES.VenNum, BILVENTASCOMPONENTES.ProIde, BILVENTASCOMPONENTES.VenDetTicDecIde,   "
            + "                                                   BILVENTASCOMPONENTES.VenDetTicVal, BILVENTASCOMPONENTES.VenDetTicCan, BILVENTASCOMPONENTES.VenDetTicPorApl,   "
            + "                                                   BILVENTASCOMPONENTES.VenDetTicProIde, BILVENTASRESPONSABLES.VenDetTicPerCofIde,   "
            + "                                                   BILVENTASRESPONSABLES.VenDetTicTerIde, BILVENTASCOMPONENTES.VenDetTicValDes, proProducto.CodProducto,   "
            + "                                                   proProducto.NomProducto, proProducto.IdGrupo, proGrupoProducto.NomGrupo, proProducto.IdProductoTipo  "
            + "                            FROM          BILVENTASCOMPONENTES WITH (NOLOCK) INNER JOIN  "
            + "                                                   BILVENTASRESPONSABLES WITH (NOLOCK) ON BILVENTASCOMPONENTES.EntCod = BILVENTASRESPONSABLES.EntCod AND   "
            + "                                                   BILVENTASCOMPONENTES.VenTraIde = BILVENTASRESPONSABLES.VenTraIde AND   "
            + "                                                   BILVENTASCOMPONENTES.VenNum = BILVENTASRESPONSABLES.VenNum AND   "
            + "                                                   BILVENTASCOMPONENTES.ProIde = BILVENTASRESPONSABLES.ProIde AND   "
            + "                                                   BILVENTASCOMPONENTES.VenDetLot = BILVENTASRESPONSABLES.VenDetLot AND   "
            + "                                                   BILVENTASCOMPONENTES.TicCod = BILVENTASRESPONSABLES.TicCod INNER JOIN  "
            + "                                                   proProducto ON BILVENTASCOMPONENTES.VenDetTicProIde = proProducto.IdProducto INNER JOIN  "
            + "                                                   proGrupoProducto ON proProducto.IdGrupo = proGrupoProducto.IdGrupo  "
            + "                            WHERE      (BILVENTASCOMPONENTES.VenNum IN  "
            + "                                                       (SELECT     BILVENTAS_1.VenNum  "
            + "                                                         FROM          BILVENTAS AS BILVENTAS_1 WITH (NOLOCK) INNER JOIN  "
            + "                                                                                BILVENTASDETALLE AS BILVENTASDETALLE_1 WITH (NOLOCK) ON   "
            + "                                                                                BILVENTAS_1.EntCod = BILVENTASDETALLE_1.EntCod AND   "
            + "                                                                                BILVENTAS_1.VenTraIde = BILVENTASDETALLE_1.VenTraIde AND   "
            + "                                                                                BILVENTAS_1.VenNum = BILVENTASDETALLE_1.VenNum  "
            + "                                                         WHERE      (BILVENTAS_1.VenEst IN ('S')) and (BILVENTAS_1.VenFec)<= @fechaActual "
            + "																	AND (BILVENTASDETALLE_1.TipIde = 5)  "
            + "                                                         GROUP BY BILVENTAS_1.SubAteIde, BILVENTASDETALLE_1.ProIde, BILVENTAS_1.VenFec, BILVENTAS_1.VenNum,   "
            + "                                                                                BILVENTASDETALLE_1.VenDetValDes, BILVENTASDETALLE_1.VenDetDecIde, BILVENTASDETALLE_1.VenDetCofIde,   "
            + "                                                                                BILVENTASDETALLE_1.TipIde))) AS C ON genTercero.IdTercero = C.VenDetTicTerIde INNER JOIN  "
            + "                      BILCONFIGURACIONHONO ON C.VenDetTicPerCofIde = BILCONFIGURACIONHONO.CofIde left OUTER JOIN  "
            + "                      BILCONTRATOSDESCUENTOS ON C.VenDetTicDecIde = BILCONTRATOSDESCUENTOS.DecIde left OUTER JOIN  "
            + "                      conContrato INNER JOIN  "
            + "                      BILVENTAS WITH (NOLOCK) INNER JOIN  "
            + "                      BILVENTASDETALLE WITH (NOLOCK) ON BILVENTAS.EntCod = BILVENTASDETALLE.EntCod AND   "
            + "                      BILVENTAS.VenTraIde = BILVENTASDETALLE.VenTraIde AND BILVENTAS.VenNum = BILVENTASDETALLE.VenNum INNER JOIN  "
            + "                      admAtencion WITH (NOLOCK) ON BILVENTAS.SubAteIde = admAtencion.IdAtencion INNER JOIN  "
            + "                      admCliente WITH (NOLOCK) ON admAtencion.IdCliente = admCliente.IdCliente ON conContrato.IdContrato = BILVENTAS.SubConIde INNER JOIN  "
            + "                      genTercero AS genTercero_1 ON conContrato.IdTercero = genTercero_1.IdTercero ON C.VenNum = BILVENTAS.VenNum  "
            + "WHERE     (BILVENTAS.VenEst IN ('S')) and (BILVENTAS.VenFec)<= @fechaActual "
            + "						AND(BILVENTASDETALLE.TipIde = 5)  "
            + "GROUP BY BILVENTAS.SubAteIde, BILVENTASDETALLE.ProIde, BILVENTAS.VenFec, BILVENTAS.VenNum, BILVENTASDETALLE.VenDetValDes,   "
            + "                      BILVENTASDETALLE.VenDetDecIde, BILVENTASDETALLE.VenDetCofIde, C.VenNum, C.VenDetTicDecIde, C.VenDetTicVal, C.VenDetTicCan,   "
            + "                      C.VenDetTicProIde, C.VenDetTicPerCofIde, C.VenDetTicTerIde, C.VenDetTicValDes, C.CodProducto, C.NomProducto, C.IdGrupo, C.NomGrupo,   "
            + "                      C.IdProductoTipo, C.ProIde, admAtencion.FecIngreso, admCliente.ApeCliente, admCliente.NomCliente, admCliente.NumDocumento,   "
            + "                      admAtencion.IndActivado, conContrato.IdContrato, conContrato.DesContrato, genTercero_1.NomTercero, genTercero.NomTercero,   "
            + "                      conContrato.IdTercero, BILVENTAS.VenUbiEnt, BILCONTRATOSDESCUENTOS.DecIde, BILCONTRATOSDESCUENTOS.DecVal,   "
            + "                      BILCONFIGURACIONHONO.CofPorTar, BILCONFIGURACIONHONO.CofPorDes, BILCONFIGURACIONHONO.CofPorTra, admAtencion.FecEgreso,   "
            + "                      admAtencion.IdUbicacionActual)as A  "
            + "  "
            + "  "
            + "update #TMP_BilVentasPendientes   "
            + "set #TMP_BilVentasPendientes.FecEgreso=#TMP_BilVentasPendientes.FechaRegistro  "
            + "where #TMP_BilVentasPendientes.FecEgreso is null and (#TMP_BilVentasPendientes.FechaRegistro)<=@fechaActual  "
            + "  "
            + "  "
            + "select a.* into #TMP_pendientes  "
            + "from(  "
            + "SELECT     BilVentasPendientes.FechaRegistro, ISNULL(BilVentasPendientes.IdAtencion, '') AS IdAtencion, BilVentasPendientes.Causacion,   "
            + "                      SUM(BilVentasPendientes.Causacion - BilVentasPendientes.Causacion * (ISNULL(BilVentasPendientes.DecVal, 0) / 100)) AS Neto,   "
            + "                      BilVentasPendientes.CodProducto, BilVentasPendientes.NomProducto, BilVentasPendientes.Paciente, BilVentasPendientes.NumDocumento,   "
            + "                      BilVentasPendientes.IndActivado, BilVentasPendientes.NomTercero, BilVentasPendientes.NomProductoTipo, BilVentasPendientes.NomGrupo,   "
            + "                      BilVentasPendientes.VenFec, BilVentasPendientes.VenDetValDes, BilVentasPendientes.VenDetCofIde, BilVentasPendientes.VenDetDecIde,   "
            + "                      BilVentasPendientes.DecIde, BilVentasPendientes.DecVal, BilVentasPendientes.Resp AS Tercero, BilVentasPendientes.TerIde,   "
            + "                      BilVentasPendientes.CofPorTar, BilVentasPendientes.CofPorDes, BilVentasPendientes.CofPorTra,   "
            + "                      SUM(BilVentasPendientes.Causacion - BilVentasPendientes.Causacion * (ISNULL(BilVentasPendientes.DecVal, 0) / 100))   "
            + "                      * (ISNULL(BilVentasPendientes.CofPorDes, 0) / 100) AS PorcTer, BilVentasPendientes.DesContrato, BilVentasPendientes.VenNum, 0 AS Estancia, genUbicacion1.NomUbicacion, CNT_CCOS1.cod_ccos,   "
            + "                      CNT_CCOS1.nom_ccos, BilVentasPendientes.idgrupo,null as cuenta  "
            + "FROM       genUbicacion as  genUbicacion1 INNER JOIN  "
            + "                   #TMP_BilVentasPendientes as    BilVentasPendientes WITH (nolock) ON genUbicacion1.IdUbicacion = BilVentasPendientes.VenUbiCon INNER JOIN  "
            + "                      CNT_CCOS as CNT_CCOS1 ON genUbicacion1.IdCCosto = CNT_CCOS1.idCCosto  "
            + "WHERE     (BilVentasPendientes.NomGrupo <> '0 <No Definido>') and cod_esor='0108'    "
            + "GROUP BY BilVentasPendientes.FechaRegistro, BilVentasPendientes.IdAtencion, BilVentasPendientes.Causacion, BilVentasPendientes.CodProducto,   "
            + "                      BilVentasPendientes.NomProducto, BilVentasPendientes.Paciente, BilVentasPendientes.NumDocumento, BilVentasPendientes.IndActivado,   "
            + "                      BilVentasPendientes.NomTercero, BilVentasPendientes.NomProductoTipo, BilVentasPendientes.NomGrupo, BilVentasPendientes.VenFec,   "
            + "                      BilVentasPendientes.VenDetValDes, BilVentasPendientes.VenDetCofIde, BilVentasPendientes.VenDetDecIde, BilVentasPendientes.DecIde,   "
            + "                      BilVentasPendientes.DecVal, BilVentasPendientes.TerIde, BilVentasPendientes.CofPorTar, BilVentasPendientes.CofPorDes,   "
            + "                      BilVentasPendientes.CofPorTra, BilVentasPendientes.Resp, BilVentasPendientes.DesContrato, BilVentasPendientes.VenNum,   "
            + "                      BilVentasPendientes.FecEgreso, BilVentasPendientes.FecIngreso, genUbicacion1.NomUbicacion, CNT_CCOS1.cod_ccos, CNT_CCOS1.nom_ccos,BilVentasPendientes.idgrupo  "
            + "  "
            + "union all  "
            + "  "
            + "SELECT     BilVentasPendientes.FechaRegistro, ISNULL(BilVentasPendientes.IdAtencion, '') AS IdAtencion, BilVentasPendientes.Causacion,   "
            + "                      SUM(BilVentasPendientes.Causacion - BilVentasPendientes.Causacion * (ISNULL(BilVentasPendientes.DecVal, 0) / 100)) AS Neto,   "
            + "                      BilVentasPendientes.CodProducto, BilVentasPendientes.NomProducto, BilVentasPendientes.Paciente, BilVentasPendientes.NumDocumento,   "
            + "                      BilVentasPendientes.IndActivado, BilVentasPendientes.NomTercero, BilVentasPendientes.NomProductoTipo, BilVentasPendientes.NomGrupo,   "
            + "                      BilVentasPendientes.VenFec, BilVentasPendientes.VenDetValDes, BilVentasPendientes.VenDetCofIde, BilVentasPendientes.VenDetDecIde,   "
            + "                      BilVentasPendientes.DecIde, BilVentasPendientes.DecVal, BilVentasPendientes.Resp AS Tercero, BilVentasPendientes.TerIde,   "
            + "                      BilVentasPendientes.CofPorTar, BilVentasPendientes.CofPorDes, BilVentasPendientes.CofPorTra,   "
            + "                      SUM(BilVentasPendientes.Causacion - BilVentasPendientes.Causacion * (ISNULL(BilVentasPendientes.DecVal, 0) / 100))   "
            + "                      * (ISNULL(BilVentasPendientes.CofPorDes, 0) / 100) AS PorcTer, BilVentasPendientes.DesContrato, BilVentasPendientes.VenNum, DATEDIFF(dd,   "
            + "                      BilVentasPendientes.FecIngreso, BilVentasPendientes.FecEgreso) AS Estancia, genUbicacion1.NomUbicacion, CNT_CCOS1.cod_ccos,   "
            + "                      CNT_CCOS1.nom_ccos,BilVentasPendientes.idgrupo,null as cuenta  "
            + "FROM       genUbicacion as  genUbicacion1 INNER JOIN  "
            + "                     #TMP_BilVentasPendientes as BilVentasPendientes WITH (nolock) ON genUbicacion1.IdUbicacion = BilVentasPendientes.VenUbiCon INNER JOIN  "
            + "                      CNT_CCOS as CNT_CCOS1 ON genUbicacion1.IdCCosto = CNT_CCOS1.idCCosto  "
            + "WHERE     (BilVentasPendientes.NomGrupo <> '0 <No Definido>') and cod_esor<>'0108'  "
            + "GROUP BY BilVentasPendientes.FechaRegistro, BilVentasPendientes.IdAtencion, BilVentasPendientes.Causacion, BilVentasPendientes.CodProducto,   "
            + "                      BilVentasPendientes.NomProducto, BilVentasPendientes.Paciente, BilVentasPendientes.NumDocumento, BilVentasPendientes.IndActivado,   "
            + "                      BilVentasPendientes.NomTercero, BilVentasPendientes.NomProductoTipo, BilVentasPendientes.NomGrupo, BilVentasPendientes.VenFec,   "
            + "                      BilVentasPendientes.VenDetValDes, BilVentasPendientes.VenDetCofIde, BilVentasPendientes.VenDetDecIde, BilVentasPendientes.DecIde,   "
            + "                      BilVentasPendientes.DecVal, BilVentasPendientes.TerIde, BilVentasPendientes.CofPorTar, BilVentasPendientes.CofPorDes,   "
            + "                      BilVentasPendientes.CofPorTra, BilVentasPendientes.Resp, BilVentasPendientes.DesContrato, BilVentasPendientes.VenNum,   "
            + "                      BilVentasPendientes.FecEgreso, BilVentasPendientes.FecIngreso, genUbicacion1.NomUbicacion, CNT_CCOS1.cod_ccos, CNT_CCOS1.nom_ccos,BilVentasPendientes.idgrupo  "
            + ") as a  "
            + "update #TMP_pendientes  "
            + "set cuenta = c.cuenta  "
            + "from #TMP_pendientes as b left join cuentasgrupos as c on b.cod_ccos=c.ccos and b.idgrupo=c.idgrupo  "
            + "where c.ccos is not null  "
            + "  "
            + "update #TMP_pendientes  "
            + "set cuenta = c.cuenta  "
            + "from #TMP_pendientes as b left join cuentasgrupos as c on  b.idgrupo=c.idgrupo  "
            + "where c.ccos is  null";

    public static String SQL_INICIO_COLINA = "declare @fechaActual datetime= '???'  \n"
            + "            SELECT A.* INTO  #TMP_BilVentasPendientes  \n"
            + "            FROM  \n"
            + "            (  \n"
            + "            SELECT     GETDATE() AS FechaRegistro, admAtencion.IdAtencion, SUM(Ventas.vrVentas) AS Causacion, proProducto.CodProducto, proProducto.NomProducto,   \n"
            + "                                  admCliente.ApeCliente + ' ' + admCliente.NomCliente AS Paciente, admCliente.NumDocumento, admAtencion.IndActivado, genTercero.NomTercero,   \n"
            + "                                  proProductoTipo.NomProductoTipo, proGrupoProducto.NomGrupo, Ventas.VenFec, Ventas.VenNum, Ventas.VenUbiCon, Ventas.VenDetValDes,   \n"
            + "                                  Ventas.VenDetCofIde, Ventas.VenDetDecIde, BILCONTRATOSDESCUENTOS.DecIde, BILCONTRATOSDESCUENTOS.DecVal,   \n"
            + "                                  BILCONFIGURACIONHONO.TerIde, BILCONFIGURACIONHONO.CofPorTar, BILCONFIGURACIONHONO.CofPorDes, BILCONFIGURACIONHONO.CofPorTra,   \n"
            + "                                  proProducto.IdProducto, proGrupoProducto.IdGrupo, proProductoTipo.IdProductoTipo, admAtencion.FecIngreso, genTercero.IdTercero,   \n"
            + "                                  conContrato.DesContrato, admAtencion.IdUbicacionActual, BILCONTRATOSDESCUENTOS.DecProIde, genTercero_1.NomTercero AS Resp,   \n"
            + "                                  conContrato.IdContrato, admAtencion.FecEgreso  \n"
            + "            FROM         [SAHICLC].[COL_CTY].[dbo].proGrupoProducto INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].proProducto ON proGrupoProducto.IdGrupo = proProducto.IdGrupo INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].proProductoTipo ON proProducto.IdProductoTipo = proProductoTipo.IdProductoTipo RIGHT OUTER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].genTercero AS genTercero_1 INNER JOIN  \n"
            + "                                      (SELECT     BILVENTASDETALLE.VenDetDecIde, BILVENTASDETALLE.VenDetCofIde, BILVENTAS.VenFec, BILVENTAS.VenNum,   \n"
            + "                                                               BILVENTAS.VenUbiCon, BILVENTASDETALLE.VenDetValDes, BILVENTAS.SubAteIde, BILVENTASDETALLE.ProIde,   \n"
            + "                                                               SUM((BILVENTASDETALLE.VenDetCan - BILVENTASDETALLE.VenDetCanDev)   \n"
            + "                                                               * BILVENTASDETALLE.VenDetVal + BILVENTASDETALLE.VenDetValRec - BILVENTASDETALLE.VenDetValDes) AS vrVentas  \n"
            + "                                        FROM          [SAHICLC].[COL_CTY].[dbo].BILVENTAS WITH (NOLOCK) INNER JOIN  \n"
            + "                                                               [SAHICLC].[COL_CTY].[dbo].BILVENTASDETALLE WITH (NOLOCK) ON BILVENTAS.EntCod = BILVENTASDETALLE.EntCod AND   \n"
            + "                                                               BILVENTAS.VenTraIde = BILVENTASDETALLE.VenTraIde AND BILVENTAS.VenNum = BILVENTASDETALLE.VenNum  \n"
            + "                                        WHERE      (BILVENTAS.VenEst IN ('S')) and (BILVENTAS.VenFec)<= @fechaActual \n"
            + "                                        GROUP BY BILVENTAS.SubAteIde, BILVENTASDETALLE.ProIde, BILVENTAS.VenFec, BILVENTAS.VenNum, BILVENTAS.VenUbiCon,   \n"
            + "                                                               BILVENTASDETALLE.VenDetValDes, BILVENTASDETALLE.VenDetDecIde, BILVENTASDETALLE.VenDetCofIde  \n"
            + "                                        UNION ALL  \n"
            + "                                        SELECT     VenDetCofIde, VenDetDecIde, VenFec, VenNum, VenUbiCon,VenDetValDes, SubAteIde, ProIde,  SUM(vrVentas) AS vrVentas  \n"
            + "                                        FROM         (SELECT     (SELECT     (BILVENTASDETALLE_1.VenDetCan - BILVENTASDETALLE_1.VenDetCanDev - ISNULL  \n"
            + "                                                                                                                  ((SELECT     SUM(BILFACTURADETALLE.FacDetCan) AS Expr1  \n"
            + "                                                                                                                      FROM         [SAHICLC].[COL_CTY].[dbo].BILFACTURADETALLE WITH (nolock) INNER JOIN  \n"
            + "                                                                                                                                            [SAHICLC].[COL_CTY].[dbo].BILFACTURA WITH (nolock) ON BILFACTURADETALLE.EntCod = BILFACTURA.EntCod AND   \n"
            + "                                                                                                                                            BILFACTURADETALLE.FacSecCod = BILFACTURA.FacSecCod AND   \n"
            + "                                                                                                                                            BILFACTURADETALLE.FacNum = BILFACTURA.FacNum AND   \n"
            + "                                                                                                                                            BILFACTURADETALLE.FacTimIde = BILFACTURA.FacTimIde AND   \n"
            + "                                                                                                                                            BILFACTURADETALLE.FacMosCod = BILFACTURA.FacMosCod AND   \n"
            + "                                                                                                                                            BILFACTURADETALLE.VenTraIde = BILVENTASDETALLE_1.VenTraIde AND   \n"
            + "                                                                                                                                            BILFACTURADETALLE.VenNum = BILVENTASDETALLE_1.VenNum AND   \n"
            + "                                                                                                                                            BILFACTURADETALLE.ProIde = BILVENTASDETALLE_1.ProIde AND   \n"
            + "                                                                                                                                            BILFACTURADETALLE.VenDetLot = BILVENTASDETALLE_1.VenDetLot  \n"
            + "                                                                                                                      WHERE     (BILFACTURA.FacEst <> 'E')), 0))   \n"
            + "                                                                                                              * BILVENTASDETALLE_1.VenDetVal + BILVENTASDETALLE_1.VenDetValRec - BILVENTASDETALLE_1.VenDetValDes AS  \n"
            + "                                                                                                               X) AS vrVentas, BILVENTASDETALLE_1.ProIde, BILVENTAS_1.SubAteIde, BILVENTAS_1.VenFec,   \n"
            + "                                                                                      BILVENTAS_1.VenNum, BILVENTAS_1.VenUbiCon, BILVENTAS_1.VenEst, BILVENTASDETALLE_1.VenDetValDes,   \n"
            + "                                                                                      BILVENTASDETALLE_1.VenDetDecIde, BILVENTASDETALLE_1.VenDetCofIde  \n"
            + "                                                               FROM          [SAHICLC].[COL_CTY].[dbo].BILVENTAS AS BILVENTAS_1 WITH (NOLOCK) INNER JOIN  \n"
            + "                                                                                      [SAHICLC].[COL_CTY].[dbo].BILVENTASDETALLE AS BILVENTASDETALLE_1 WITH (NOLOCK) ON   \n"
            + "                                                                                      BILVENTAS_1.EntCod = BILVENTASDETALLE_1.EntCod AND BILVENTAS_1.VenTraIde = BILVENTASDETALLE_1.VenTraIde AND   \n"
            + "                                                                                      BILVENTAS_1.VenNum = BILVENTASDETALLE_1.VenNum  \n"
            + "                                                               WHERE      (BILVENTAS_1.VenEst IN ('P')) and (BILVENTAS_1.VenFec)<= @fechaActual  \n"
            + "            																) AS VentasParciales  \n"
            + "                                        GROUP BY SubAteIde, ProIde, VenFec, VenNum, VenUbiCon, VenDetValDes, VenDetDecIde, VenDetCofIde) AS Ventas INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].BILCONFIGURACIONHONO ON Ventas.VenDetCofIde = BILCONFIGURACIONHONO.CofIde ON   \n"
            + "                                  genTercero_1.IdTercero = BILCONFIGURACIONHONO.TerIde LEFT OUTER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].BILCONTRATOSDESCUENTOS ON Ventas.VenDetDecIde = BILCONTRATOSDESCUENTOS.DecIde ON   \n"
            + "                                  proProducto.IdProducto = Ventas.ProIde LEFT OUTER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].genUbicacion INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].genTercero WITH (nolock) INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].conContrato ON genTercero.IdTercero = conContrato.IdTercero INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].ADMATENCIONESVINCULA WITH (nolock) INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].admCliente WITH (nolock) INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].admAtencion WITH (nolock) ON admCliente.IdCliente = admAtencion.IdCliente ON ADMATENCIONESVINCULA.AteIde = admAtencion.IdAtencion ON   \n"
            + "                                  conContrato.IdContrato = ADMATENCIONESVINCULA.ConIde ON genUbicacion.IdUbicacion = admAtencion.IdUbicacionActual ON   \n"
            + "                                  Ventas.SubAteIde = admAtencion.IdAtencion AND ADMATENCIONESVINCULA.AtnOrdPri = 1 AND ADMATENCIONESVINCULA.AtnIndAct = 1  \n"
            + "            GROUP BY admAtencion.IdAtencion, proProducto.CodProducto, proProducto.NomProducto, admCliente.ApeCliente, admCliente.NomCliente,   \n"
            + "                                  admCliente.NumDocumento, admAtencion.IndActivado, genTercero.NomTercero, proProductoTipo.NomProductoTipo, proGrupoProducto.NomGrupo,   \n"
            + "                                  Ventas.VenFec, Ventas.VenNum, Ventas.VenUbiCon, Ventas.VenDetValDes, Ventas.VenDetDecIde, BILCONTRATOSDESCUENTOS.DecIde,   \n"
            + "                                  BILCONTRATOSDESCUENTOS.DecVal, Ventas.VenDetCofIde, BILCONFIGURACIONHONO.TerIde, BILCONFIGURACIONHONO.CofPorTar,   \n"
            + "                                  BILCONFIGURACIONHONO.CofPorDes, BILCONFIGURACIONHONO.CofPorTra, proProducto.IdProducto, proGrupoProducto.IdGrupo,   \n"
            + "                                  proProductoTipo.IdProductoTipo, admAtencion.FecIngreso, genTercero.IdTercero, conContrato.DesContrato, admAtencion.IdUbicacionActual,   \n"
            + "                                  BILCONTRATOSDESCUENTOS.DecProIde, genTercero_1.NomTercero, conContrato.IdContrato, admAtencion.FecEgreso  \n"
            + "              \n"
            + "            UNION ALL  \n"
            + "            SELECT DISTINCT   \n"
            + "                                  GETDATE() AS FechaRegistro, BILVENTAS.SubAteIde, SUM(C.VenDetTicCan * C.VenDetTicVal) AS causacion, C.CodProducto, C.NomProducto,   \n"
            + "                                  admCliente.ApeCliente + ' ' + admCliente.NomCliente AS paciente, admCliente.NumDocumento, admAtencion.IndActivado, genTercero_1.NomTercero,   \n"
            + "                                  'Componentes' AS NomProductoTipo, C.NomGrupo, BILVENTAS.VenFec, BILVENTAS.VenNum,BILVENTAS.VenUbiEnt, C.VenDetTicValDes, C.VenDetTicPerCofIde,   \n"
            + "                                  C.VenDetTicDecIde, BILCONTRATOSDESCUENTOS.DecIde, BILCONTRATOSDESCUENTOS.DecVal, C.VenDetTicTerIde,   \n"
            + "                                  BILCONFIGURACIONHONO.CofPorTar, BILCONFIGURACIONHONO.CofPorDes, BILCONFIGURACIONHONO.CofPorTra, C.VenDetTicProIde, C.IdGrupo,   \n"
            + "                                  C.IdProductoTipo, admAtencion.FecIngreso, conContrato.IdTercero, conContrato.DesContrato, admAtencion.IdUbicacionActual,  C.ProIde,   \n"
            + "                                  genTercero.NomTercero AS Resp, conContrato.IdContrato, admAtencion.FecEgreso  \n"
            + "            FROM         [SAHICLC].[COL_CTY].[dbo].genTercero INNER JOIN  \n"
            + "                                      (SELECT     BILVENTASCOMPONENTES.VenNum, BILVENTASCOMPONENTES.ProIde, BILVENTASCOMPONENTES.VenDetTicDecIde,   \n"
            + "                                                               BILVENTASCOMPONENTES.VenDetTicVal, BILVENTASCOMPONENTES.VenDetTicCan, BILVENTASCOMPONENTES.VenDetTicPorApl,   \n"
            + "                                                               BILVENTASCOMPONENTES.VenDetTicProIde, BILVENTASRESPONSABLES.VenDetTicPerCofIde,   \n"
            + "                                                               BILVENTASRESPONSABLES.VenDetTicTerIde, BILVENTASCOMPONENTES.VenDetTicValDes, proProducto.CodProducto,   \n"
            + "                                                               proProducto.NomProducto, proProducto.IdGrupo, proGrupoProducto.NomGrupo, proProducto.IdProductoTipo  \n"
            + "                                        FROM          [SAHICLC].[COL_CTY].[dbo].BILVENTASCOMPONENTES WITH (NOLOCK) INNER JOIN  \n"
            + "                                                               [SAHICLC].[COL_CTY].[dbo].BILVENTASRESPONSABLES WITH (NOLOCK) ON BILVENTASCOMPONENTES.EntCod = BILVENTASRESPONSABLES.EntCod AND   \n"
            + "                                                               BILVENTASCOMPONENTES.VenTraIde = BILVENTASRESPONSABLES.VenTraIde AND   \n"
            + "                                                               BILVENTASCOMPONENTES.VenNum = BILVENTASRESPONSABLES.VenNum AND   \n"
            + "                                                               BILVENTASCOMPONENTES.ProIde = BILVENTASRESPONSABLES.ProIde AND   \n"
            + "                                                               BILVENTASCOMPONENTES.VenDetLot = BILVENTASRESPONSABLES.VenDetLot AND   \n"
            + "                                                               BILVENTASCOMPONENTES.TicCod = BILVENTASRESPONSABLES.TicCod INNER JOIN  \n"
            + "                                                               [SAHICLC].[COL_CTY].[dbo].proProducto ON BILVENTASCOMPONENTES.VenDetTicProIde = proProducto.IdProducto INNER JOIN  \n"
            + "                                                               [SAHICLC].[COL_CTY].[dbo].proGrupoProducto ON proProducto.IdGrupo = proGrupoProducto.IdGrupo  \n"
            + "                                        WHERE      (BILVENTASCOMPONENTES.VenNum IN  \n"
            + "                                                                   (SELECT     BILVENTAS_1.VenNum  \n"
            + "                                                                     FROM          [SAHICLC].[COL_CTY].[dbo].BILVENTAS AS BILVENTAS_1 WITH (NOLOCK) INNER JOIN  \n"
            + "                                                                                            [SAHICLC].[COL_CTY].[dbo].BILVENTASDETALLE AS BILVENTASDETALLE_1 WITH (NOLOCK) ON   \n"
            + "                                                                                            BILVENTAS_1.EntCod = BILVENTASDETALLE_1.EntCod AND   \n"
            + "                                                                                            BILVENTAS_1.VenTraIde = BILVENTASDETALLE_1.VenTraIde AND   \n"
            + "                                                                                            BILVENTAS_1.VenNum = BILVENTASDETALLE_1.VenNum  \n"
            + "                                                                     WHERE      (BILVENTAS_1.VenEst IN ('S')) and (BILVENTAS_1.VenFec)<= @fechaActual \n"
            + "            																	AND (BILVENTASDETALLE_1.TipIde = 5)  \n"
            + "                                                                     GROUP BY BILVENTAS_1.SubAteIde, BILVENTASDETALLE_1.ProIde, BILVENTAS_1.VenFec, BILVENTAS_1.VenNum,   \n"
            + "                                                                                            BILVENTASDETALLE_1.VenDetValDes, BILVENTASDETALLE_1.VenDetDecIde, BILVENTASDETALLE_1.VenDetCofIde,   \n"
            + "                                                                                            BILVENTASDETALLE_1.TipIde))) AS C ON genTercero.IdTercero = C.VenDetTicTerIde INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].BILCONFIGURACIONHONO ON C.VenDetTicPerCofIde = BILCONFIGURACIONHONO.CofIde left OUTER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].BILCONTRATOSDESCUENTOS ON C.VenDetTicDecIde = BILCONTRATOSDESCUENTOS.DecIde left OUTER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].conContrato INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].BILVENTAS WITH (NOLOCK) INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].BILVENTASDETALLE WITH (NOLOCK) ON BILVENTAS.EntCod = BILVENTASDETALLE.EntCod AND   \n"
            + "                                  BILVENTAS.VenTraIde = BILVENTASDETALLE.VenTraIde AND BILVENTAS.VenNum = BILVENTASDETALLE.VenNum INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].admAtencion WITH (NOLOCK) ON BILVENTAS.SubAteIde = admAtencion.IdAtencion INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].admCliente WITH (NOLOCK) ON admAtencion.IdCliente = admCliente.IdCliente ON conContrato.IdContrato = BILVENTAS.SubConIde INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].genTercero AS genTercero_1 ON conContrato.IdTercero = genTercero_1.IdTercero ON C.VenNum = BILVENTAS.VenNum  \n"
            + "            WHERE     (BILVENTAS.VenEst IN ('S')) and (BILVENTAS.VenFec)<= @fechaActual \n"
            + "            						AND(BILVENTASDETALLE.TipIde = 5)  \n"
            + "            GROUP BY BILVENTAS.SubAteIde, BILVENTASDETALLE.ProIde, BILVENTAS.VenFec, BILVENTAS.VenNum, BILVENTASDETALLE.VenDetValDes,   \n"
            + "                                  BILVENTASDETALLE.VenDetDecIde, BILVENTASDETALLE.VenDetCofIde, C.VenNum, C.VenDetTicDecIde, C.VenDetTicVal, C.VenDetTicCan,   \n"
            + "                                  C.VenDetTicProIde, C.VenDetTicPerCofIde, C.VenDetTicTerIde, C.VenDetTicValDes, C.CodProducto, C.NomProducto, C.IdGrupo, C.NomGrupo,   \n"
            + "                                  C.IdProductoTipo, C.ProIde, admAtencion.FecIngreso, admCliente.ApeCliente, admCliente.NomCliente, admCliente.NumDocumento,   \n"
            + "                                  admAtencion.IndActivado, conContrato.IdContrato, conContrato.DesContrato, genTercero_1.NomTercero, genTercero.NomTercero,   \n"
            + "                                  conContrato.IdTercero, BILVENTAS.VenUbiEnt, BILCONTRATOSDESCUENTOS.DecIde, BILCONTRATOSDESCUENTOS.DecVal,   \n"
            + "                                  BILCONFIGURACIONHONO.CofPorTar, BILCONFIGURACIONHONO.CofPorDes, BILCONFIGURACIONHONO.CofPorTra, admAtencion.FecEgreso,   \n"
            + "                                  admAtencion.IdUbicacionActual)as A  \n"
            + "              \n"
            + "              \n"
            + "            update #TMP_BilVentasPendientes   \n"
            + "            set #TMP_BilVentasPendientes.FecEgreso=#TMP_BilVentasPendientes.FechaRegistro  \n"
            + "            where #TMP_BilVentasPendientes.FecEgreso is null and (#TMP_BilVentasPendientes.FechaRegistro)<=@fechaActual  \n"
            + "              \n"
            + "              \n"
            + "            select a.* into #TMP_pendientes  \n"
            + "            from(  \n"
            + "            SELECT     BilVentasPendientes.FechaRegistro, ISNULL(BilVentasPendientes.IdAtencion, '') AS IdAtencion, BilVentasPendientes.Causacion,   \n"
            + "                                  SUM(BilVentasPendientes.Causacion - BilVentasPendientes.Causacion * (ISNULL(BilVentasPendientes.DecVal, 0) / 100)) AS Neto,   \n"
            + "                                  BilVentasPendientes.CodProducto, BilVentasPendientes.NomProducto, BilVentasPendientes.Paciente, BilVentasPendientes.NumDocumento,   \n"
            + "                                  BilVentasPendientes.IndActivado, BilVentasPendientes.NomTercero, BilVentasPendientes.NomProductoTipo, BilVentasPendientes.NomGrupo,   \n"
            + "                                  BilVentasPendientes.VenFec, BilVentasPendientes.VenDetValDes, BilVentasPendientes.VenDetCofIde, BilVentasPendientes.VenDetDecIde,   \n"
            + "                                  BilVentasPendientes.DecIde, BilVentasPendientes.DecVal, BilVentasPendientes.Resp AS Tercero, BilVentasPendientes.TerIde,   \n"
            + "                                  BilVentasPendientes.CofPorTar, BilVentasPendientes.CofPorDes, BilVentasPendientes.CofPorTra,   \n"
            + "                                  SUM(BilVentasPendientes.Causacion - BilVentasPendientes.Causacion * (ISNULL(BilVentasPendientes.DecVal, 0) / 100))   \n"
            + "                                  * (ISNULL(BilVentasPendientes.CofPorDes, 0) / 100) AS PorcTer, BilVentasPendientes.DesContrato, BilVentasPendientes.VenNum, 0 AS Estancia, genUbicacion1.NomUbicacion, CNT_CCOS1.cod_ccos,   \n"
            + "                                  CNT_CCOS1.nom_ccos, BilVentasPendientes.idgrupo,null as cuenta  \n"
            + "            FROM       [SAHICLC].[COL_CTY].[dbo].genUbicacion as  genUbicacion1 INNER JOIN  \n"
            + "                               #TMP_BilVentasPendientes as    BilVentasPendientes WITH (nolock) ON genUbicacion1.IdUbicacion = BilVentasPendientes.VenUbiCon INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].CNT_CCOS as CNT_CCOS1 ON genUbicacion1.IdCCosto = CNT_CCOS1.idCCosto  \n"
            + "            WHERE     (BilVentasPendientes.NomGrupo <> '0 <No Definido>') and cod_esor='0108'    \n"
            + "            GROUP BY BilVentasPendientes.FechaRegistro, BilVentasPendientes.IdAtencion, BilVentasPendientes.Causacion, BilVentasPendientes.CodProducto,   \n"
            + "                                  BilVentasPendientes.NomProducto, BilVentasPendientes.Paciente, BilVentasPendientes.NumDocumento, BilVentasPendientes.IndActivado,   \n"
            + "                                  BilVentasPendientes.NomTercero, BilVentasPendientes.NomProductoTipo, BilVentasPendientes.NomGrupo, BilVentasPendientes.VenFec,   \n"
            + "                                  BilVentasPendientes.VenDetValDes, BilVentasPendientes.VenDetCofIde, BilVentasPendientes.VenDetDecIde, BilVentasPendientes.DecIde,   \n"
            + "                                  BilVentasPendientes.DecVal, BilVentasPendientes.TerIde, BilVentasPendientes.CofPorTar, BilVentasPendientes.CofPorDes,   \n"
            + "                                  BilVentasPendientes.CofPorTra, BilVentasPendientes.Resp, BilVentasPendientes.DesContrato, BilVentasPendientes.VenNum,   \n"
            + "                                  BilVentasPendientes.FecEgreso, BilVentasPendientes.FecIngreso, genUbicacion1.NomUbicacion, CNT_CCOS1.cod_ccos, CNT_CCOS1.nom_ccos,BilVentasPendientes.idgrupo  \n"
            + "              \n"
            + "            union all  \n"
            + "              \n"
            + "            SELECT     BilVentasPendientes.FechaRegistro, ISNULL(BilVentasPendientes.IdAtencion, '') AS IdAtencion, BilVentasPendientes.Causacion,   \n"
            + "                                  SUM(BilVentasPendientes.Causacion - BilVentasPendientes.Causacion * (ISNULL(BilVentasPendientes.DecVal, 0) / 100)) AS Neto,   \n"
            + "                                  BilVentasPendientes.CodProducto, BilVentasPendientes.NomProducto, BilVentasPendientes.Paciente, BilVentasPendientes.NumDocumento,   \n"
            + "                                  BilVentasPendientes.IndActivado, BilVentasPendientes.NomTercero, BilVentasPendientes.NomProductoTipo, BilVentasPendientes.NomGrupo,   \n"
            + "                                  BilVentasPendientes.VenFec, BilVentasPendientes.VenDetValDes, BilVentasPendientes.VenDetCofIde, BilVentasPendientes.VenDetDecIde,   \n"
            + "                                  BilVentasPendientes.DecIde, BilVentasPendientes.DecVal, BilVentasPendientes.Resp AS Tercero, BilVentasPendientes.TerIde,   \n"
            + "                                  BilVentasPendientes.CofPorTar, BilVentasPendientes.CofPorDes, BilVentasPendientes.CofPorTra,   \n"
            + "                                  SUM(BilVentasPendientes.Causacion - BilVentasPendientes.Causacion * (ISNULL(BilVentasPendientes.DecVal, 0) / 100))   \n"
            + "                                  * (ISNULL(BilVentasPendientes.CofPorDes, 0) / 100) AS PorcTer, BilVentasPendientes.DesContrato, BilVentasPendientes.VenNum, DATEDIFF(dd,   \n"
            + "                                  BilVentasPendientes.FecIngreso, BilVentasPendientes.FecEgreso) AS Estancia, genUbicacion1.NomUbicacion, CNT_CCOS1.cod_ccos,   \n"
            + "                                  CNT_CCOS1.nom_ccos,BilVentasPendientes.idgrupo,null as cuenta  \n"
            + "            FROM       [SAHICLC].[COL_CTY].[dbo].genUbicacion as  genUbicacion1 INNER JOIN  \n"
            + "                                 #TMP_BilVentasPendientes as BilVentasPendientes WITH (nolock) ON genUbicacion1.IdUbicacion = BilVentasPendientes.VenUbiCon INNER JOIN  \n"
            + "                                  [SAHICLC].[COL_CTY].[dbo].CNT_CCOS as CNT_CCOS1 ON genUbicacion1.IdCCosto = CNT_CCOS1.idCCosto  \n"
            + "            WHERE     (BilVentasPendientes.NomGrupo <> '0 <No Definido>') and cod_esor<>'0108'  \n"
            + "            GROUP BY BilVentasPendientes.FechaRegistro, BilVentasPendientes.IdAtencion, BilVentasPendientes.Causacion, BilVentasPendientes.CodProducto,   \n"
            + "                                  BilVentasPendientes.NomProducto, BilVentasPendientes.Paciente, BilVentasPendientes.NumDocumento, BilVentasPendientes.IndActivado,   \n"
            + "                                  BilVentasPendientes.NomTercero, BilVentasPendientes.NomProductoTipo, BilVentasPendientes.NomGrupo, BilVentasPendientes.VenFec,   \n"
            + "                                  BilVentasPendientes.VenDetValDes, BilVentasPendientes.VenDetCofIde, BilVentasPendientes.VenDetDecIde, BilVentasPendientes.DecIde,   \n"
            + "                                  BilVentasPendientes.DecVal, BilVentasPendientes.TerIde, BilVentasPendientes.CofPorTar, BilVentasPendientes.CofPorDes,   \n"
            + "                                  BilVentasPendientes.CofPorTra, BilVentasPendientes.Resp, BilVentasPendientes.DesContrato, BilVentasPendientes.VenNum,   \n"
            + "                                  BilVentasPendientes.FecEgreso, BilVentasPendientes.FecIngreso, genUbicacion1.NomUbicacion, CNT_CCOS1.cod_ccos, CNT_CCOS1.nom_ccos,BilVentasPendientes.idgrupo  \n"
            + "            ) as a  \n"
            + "            update #TMP_pendientes  \n"
            + "            set cuenta = c.cuenta  \n"
            + "            from #TMP_pendientes as b left join [SAHICLC].[COL_CTY].[dbo].cuentasgrupos as c on b.cod_ccos=c.ccos and b.idgrupo=c.idgrupo  \n"
            + "            where c.ccos is not null  \n"
            + "              \n"
            + "            update #TMP_pendientes  \n"
            + "            set cuenta = c.cuenta  \n"
            + "            from #TMP_pendientes as b left join [SAHICLC].[COL_CTY].[dbo].cuentasgrupos as c on  b.idgrupo=c.idgrupo  \n"
            + "            where c.ccos is  null";

    public static String SQL_SELECT = "select   "
            + "  "
            + "isnull((  "
            + "select  Sum(Neto)   "
            + "from #TMP_pendientes  "
            + " left join admatencion on admatencion.idatencion=#TMP_pendientes.idatencion  JOIN  "
            + "	admServicio ON admServicio.idServicio=AdmAtencion.IdServicio  "
            + "   where   "
            + "   AdmAtencion.IdServicio  in (4,10,11,17,18,19,20,22,23,24,30,31,32,37,38,40,44,50,51,52,53,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76       )  "
            + "   and DATEDIFF(hh, AdmAtencion.FecIngreso, getdate())>24  "
            + "group by FechaRegistro   "
            + "),0)  "
            + "+  "
            + "  "
            + "isnull(( select Sum(Neto)   "
            + "from #TMP_pendientes  "
            + " left join admatencion on admatencion.idatencion=#TMP_pendientes.idatencion  JOIN  "
            + "	admServicio ON admServicio.idServicio=AdmAtencion.IdServicio  "
            + "   where   "
            + "   AdmAtencion.IdServicio not  in (4,10,11,17,18,19,20,22,23,24,30,31,32,37,38,40,44,50,51,52,53,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76       )  "
            + "   and  AdmAtencion.FecEgreso is not null  "
            + "group by FechaRegistro   "
            + " ),0) as PorFacturarConEgreso,  "
            + "  "
            + "   "
            + "isnull((  "
            + "select sum(neto)   "
            + "from #TMP_pendientes  "
            + " left join admatencion on admatencion.idatencion=#TMP_pendientes.idatencion  JOIN  "
            + "	admServicio ON admServicio.idServicio=AdmAtencion.IdServicio  "
            + "   where   "
            + "   AdmAtencion.IdServicio  in (4,10,11,17,18,19,20,22,23,24,30,31,32,37,38,40,44,50,51,52,53,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76       )  "
            + "   and DATEDIFF(hh, AdmAtencion.FecIngreso, getdate())<24  "
            + "group by FechaRegistro   "
            + "),0)  "
            + "+  "
            + "isnull(  "
            + "( select Sum(Neto)   "
            + "from #TMP_pendientes  "
            + " left join admatencion on admatencion.idatencion=#TMP_pendientes.idatencion  JOIN  "
            + "	admServicio ON admServicio.idServicio=AdmAtencion.IdServicio  "
            + "   where   "
            + "   AdmAtencion.IdServicio not  in (4,10,11,17,18,19,20,22,23,24,30,31,32,37,38,40,44,50,51,52,53,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76       )  "
            + "   and  AdmAtencion.FecEgreso is  null  "
            + "group by FechaRegistro   "
            + " ),0) as PacientesAcostados";

    public static String SQL_SELECT_COLINA = "select   \n"
            + "            isnull((  \n"
            + "            select  Sum(Neto)   \n"
            + "            from #TMP_pendientes  \n"
            + "             left join [SAHICLC].[COL_CTY].[dbo].admatencion on admatencion.idatencion=#TMP_pendientes.idatencion  JOIN  \n"
            + "            	[SAHICLC].[COL_CTY].[dbo].admServicio ON admServicio.idServicio=AdmAtencion.IdServicio  \n"
            + "               where   \n"
            + "               AdmAtencion.IdServicio  in (4,10,11,17,18,19,20,22,23,24,30,31,32,37,38,40,44,50,51,52,53,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76       )  \n"
            + "               and DATEDIFF(hh, AdmAtencion.FecIngreso, getdate())>24  \n"
            + "            group by FechaRegistro   \n"
            + "            ),0)  \n"
            + "            +  \n"
            + "              \n"
            + "            isnull(( select Sum(Neto)   \n"
            + "            from #TMP_pendientes  \n"
            + "             left join [SAHICLC].[COL_CTY].[dbo].admatencion on admatencion.idatencion=#TMP_pendientes.idatencion  JOIN  \n"
            + "            	[SAHICLC].[COL_CTY].[dbo].admServicio ON admServicio.idServicio=AdmAtencion.IdServicio  \n"
            + "               where   \n"
            + "               AdmAtencion.IdServicio not  in (4,10,11,17,18,19,20,22,23,24,30,31,32,37,38,40,44,50,51,52,53,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76       )  \n"
            + "               and  AdmAtencion.FecEgreso is not null  \n"
            + "            group by FechaRegistro   \n"
            + "             ),0) as PorFacturarConEgreso,  \n"
            + "              \n"
            + "               \n"
            + "            isnull((  \n"
            + "            select sum(neto)   \n"
            + "            from #TMP_pendientes  \n"
            + "             left join [SAHICLC].[COL_CTY].[dbo].admatencion on admatencion.idatencion=#TMP_pendientes.idatencion  JOIN  \n"
            + "            	[SAHICLC].[COL_CTY].[dbo].admServicio ON admServicio.idServicio=AdmAtencion.IdServicio  \n"
            + "               where   \n"
            + "               AdmAtencion.IdServicio  in (4,10,11,17,18,19,20,22,23,24,30,31,32,37,38,40,44,50,51,52,53,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76       )  \n"
            + "               and DATEDIFF(hh, AdmAtencion.FecIngreso, getdate())<24  \n"
            + "            group by FechaRegistro   \n"
            + "            ),0)  \n"
            + "            +  \n"
            + "            isnull(  \n"
            + "            ( select Sum(Neto)   \n"
            + "            from #TMP_pendientes  \n"
            + "             left join [SAHICLC].[COL_CTY].[dbo].admatencion on admatencion.idatencion=#TMP_pendientes.idatencion  JOIN  \n"
            + "            	[SAHICLC].[COL_CTY].[dbo].admServicio ON admServicio.idServicio=AdmAtencion.IdServicio  \n"
            + "               where   \n"
            + "               AdmAtencion.IdServicio not  in (4,10,11,17,18,19,20,22,23,24,30,31,32,37,38,40,44,50,51,52,53,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76       )  \n"
            + "               and  AdmAtencion.FecEgreso is  null  \n"
            + "            group by FechaRegistro   \n"
            + "             ),0) as PacientesAcostados";

    public static String SQL_DROP = "drop table  #TMP_BilVentasPendientes  "
            + "drop table #TMP_pendientes  ";

    public static String SQL_DROP_COLINA = "drop table  #TMP_BilVentasPendientes  "
            + "drop table #TMP_pendientes  ";
}
